<?php

/**
 * @file
 * The OpenScholar Help module provides inline help links with popup docs.
 */

/**
 * Implements hook_process_HOOK for page.tpl.php.
 */
function os_help_process_page(&$vars) {
  module_load_include('inc', 'os_help.cp');
  // Only continues for authenticated users.
  if (user_is_anonymous()) {
    return;
  }

  // Adds link for the `help` page region based on the current path.
  module_load_include('inc', 'os_help');
  $path = drupal_get_path_alias();
  if ($variables = os_help_get_variables_from_id('path', $path)) {
    $vars['page']['help'] = theme_link($variables);
    drupal_add_css(drupal_get_path('module', 'os_help') . '/os_help.css');
  }
}

/**
 * Implements hook_form_FORM_ID_form_alter() for spaces_features_form
 */
function os_help_form_spaces_features_form_alter(&$form, &$form_state, $form_id) {
  module_load_include('inc', 'os_help');
  foreach ($form['spaces_features'] as $app => $element) {
    if (isset($element['#type']) && $element['#type'] == 'select') {
      if ($variables = os_help_get_variables_from_id('app', $app)) {
        $form['spaces_features'][$app]['#description'] = theme_link($variables);
      }
    }
  }
}

function os_help_rest_cp_settings_submit($var, $value) {

  $values['sender'] = $user;
  $values['sender']->name = variable_get('os_support_name');
  $values['sender']->mail = variable_get('os_support_mail');
  $values['category'] = contact_load(variable_get('os_support_cid'));
  $values['copy'] = variable_get('os_support_copy');
  $values['message'] = variable_get('os_support_message');
  $values['subject'] = variable_get('os_support_subject');

  // Get the to and from e-mail addresses.
  $to = $values['category']['recipients'];
  $from = $values['sender']->mail;

  // Send the e-mail to the recipients using the site default language.
  drupal_mail('contact', 'page_mail', $to, language_default(), $values, $from);

  // If the user requests it, send a copy using the current language.
  if ($values['copy']) {
    drupal_mail('contact', 'page_copy', $from, $language, $values, $from);
  }
  variable_del('os_support_name');
  variable_del('os_support_mail');
  variable_del('os_support_cid');
  variable_del('os_support_copy');
  variable_del('os_support_message');
  variable_del('os_support_subject');
  flood_register_event('contact', variable_get('contact_threshold_window', 3600));
}

function os_help_contact_form_validate($value) {
  if (!empty($value)) {
    return true;
  }
  return false;
}