<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function os_restful_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return 'plugins/' . $plugin;
  }
  if ($module == 'entity_validator') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function os_restful_entity_info_alter(&$entity_info) {
  $entity_info['user']['entity keys']['label'] = 'name';
}
