<?php

/**
 * @file
 * OS Revisions module file.
 */

/**
 * Define URL for OpenScholar revisions documentation
 */
define('OS_REVISIONS_DOCS_URL', 'http://docs.openscholar.harvard.edu');

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form.
 */
function os_revisions_form_node_form_alter(&$form, $form_state) {
  $content_type = $form['#node']->type;

  if (!variable_get("enable_revisions_$content_type", FALSE)) {
    $form['revision_information']['#access'] = FALSE;
  }
  else {
    $form['revision_information']['revision']['#weight'] = 1;
    $form['revision_information']['log']['#weight'] = 2;
    $form['revision_information']['log']['#title'] = t('Revision Notes');
    $form['revision_information']['log']['#description'] = t('Provide an explanation of the changes you are making.') . '<br><br>' . l(t('What’s being stored as a revision?'), OS_REVISIONS_DOCS_URL, array('attributes' => array('target' => '_blank', 'rel' => 'noopener')));

    // if there are revisions, show them
    $num_revisions = count(node_revision_list($form['#node'])) - 1;
    if ($num_revisions > 1) {
      $revisions_url = "node/" . $form['#node']->nid . "/revisions";
      $form['revision_information']['info']['#markup'] = t('<p>There are currently <a href="@url" id="revisions-link">@num revisions</a>.</p>', array('@url' => url($revisions_url), '@num' => $num_revisions));
      $form['revision_information']['info']['#weight'] = 0;
    }

  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * Removes purl from hook_init's implementations queue since it was already run
 * during custom_theme.
 */
function os_revisions_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_node_form_alter') {
    unset($implementations['os_revisions']);
    $implementations = array_merge(array('os_revisions' => FALSE), $implementations);
  }
}

/**
 * Implements hook_menu().
 */
function os_revisions_menu() {
  $items = array();
  $items['node/%node/revisions'] = array(
    'title' => 'Revisions',
    'page callback' => 'os_revisions_revision_overview',
    'page arguments' => array(1),
    'access callback' => '_node_revision_access',
    'access arguments' => array(1),
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Re-write the list of revisions for a node
 */
function os_revisions_revision_overview($node) {
  drupal_set_title(t('Revisions for %title', array('%title' => $node->title)), PASS_THROUGH);

  $header = array(t('Revision'), array('data' => t('Manage'), 'colspan' => 2));

  $revisions = node_revision_list($node);

  $rows = array();
  $revert_permission = FALSE;
  if ((user_access('revert revisions') || user_access('administer nodes')) && node_access('update', $node)) {
    $revert_permission = TRUE;
  }
  $delete_permission = FALSE;
  if ((user_access('delete revisions') || user_access('administer nodes')) && node_access('delete', $node)) {
    $delete_permission = TRUE;
  }
  foreach ($revisions as $revision) {
    $row = array();
    $operations = array();

    if ($revision->current_vid > 0) {

      $row[] = array('data' => t('!date by !username', array('!date' => l(format_date($revision->timestamp, 'short'), "node/$node->nid/revisions/$revision->vid/view"), '!username' => theme('username', array('account' => $revision))))
        . (($revision->log != '') ? '<p class="revision-log">' . filter_xss($revision->log) . '</p>' : ''),
        'class' => array('revision-current'));
      $operations[] = array('data' => drupal_placeholder(t('Current revision')), 'class' => array('revision-current'), 'colspan' => 2);
    }
    else {
      $row[] = t('!date by !username', array('!date' => format_date($revision->timestamp, 'short'), '!username' => theme('username', array('account' => $revision))))
        . (($revision->log != '') ? '<p class="revision-log">' . filter_xss($revision->log) . '</p>' : '');
      if ($revert_permission) {
        $operations[] = l(t('Revert'), "node/$node->nid/revisions/$revision->vid/revert");
      }
      if ($delete_permission) {
        $operations[] = l(t('Delete'), "node/$node->nid/revisions/$revision->vid/delete");
      }
    }
    $rows[] = array_merge($row, $operations);
  }

  $limit = variable_get("restrict_node_revision_number_for_" . str_replace("-", "_", $node->type), FALSE);

  $build['node_revisions_table'] = array(
    '#theme' => 'table',
    '#rows' => $rows,
    '#header' => $header,
    '#caption' => t('NOTE: When you revert to a prior revision, a new copy is created based on that revision. Maximum of @limit revisions allowed.', array('@limit' => $limit)) . ' ' . l(t('Learn more about revisions'), OS_REVISIONS_DOCS_URL),
  );

  return $build;
}

/**
 * Implements hook_form_alter().
 *
 * Add revision information in hidden fields and javascript to check if the user has reached the max # of revisions for the node
 */
function os_revisions_form_alter(&$form, &$form_state, $form_id){
  $node_edit_forms = array(
    'biblio_node_form',
    'blog_node_form',
    'book_node_form',
    'faq_node_form',
    'link_node_form',
    'news_node_form',
    'page_node_form',
    'person_node_form',
  );

  if (in_array($form_id, $node_edit_forms) && $form_state['node']->nid) {
    $max_revisions = (int)variable_get("restrict_node_revision_number_for_" . str_replace("-", "_", $form_state['node']->type), FALSE);
    if ($max_revisions) {
      $form['max_revisions'] = array('#type' => 'hidden', '#value' => $max_revisions);
      $form['revisions'] =  array('#type' => 'hidden', '#value' => (count(node_revision_list(node_load($form_state['node']->nid))) - 1));
      $form['#attached']['js'][] = drupal_get_path('module', 'os_revisions') . '/os_revisions.js';
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * Change title/text in confirm_form when user selects to revert to an older revision
 */
function os_revisions_form_node_revision_revert_confirm_alter(&$form, &$form_state, $form_id) {
  $text = drupal_get_title();
  drupal_set_title(t('Confirm Revert'));
  $form['description'] = array(
    '#markup' => "<p>$text</p>",
  );

  // replace existing submit handler that creates the revert revision log with one that maintains revision log message
  $submit_handlers = array_flip($form['#submit']);
  $submit_index = $submit_handlers['node_revision_revert_confirm_submit'];
  $form['#submit'][$submit_index] = 'os_revisions_add_revert_notes';
}

/**
 * Implements hook_form_alter().
 *
 * Change title/text in confirm_form when user selects to delete a revision
 */
function os_revisions_form_node_revision_delete_confirm_alter(&$form, &$form_state, $form_id) {
  $text = drupal_get_title();
  drupal_set_title(t('Confirm Delete'));
  $form['description'] = array(
    '#markup' => "<p>$text</p>",
  );
}

/**
 * Submit handler for node_revision_revert_confirm form to append revision notes
 * from the reverted revision to the new revision notes
 */
function os_revisions_add_revert_notes($form, &$form_state) {
  $node_revision = $form['#node_revision'];
  $node_revision->revision = 1;
  $old_log = $node_revision->log;
  $node_revision->log = t('Copy of the revision from %date: %log.', array('%date' => format_date($node_revision->revision_timestamp), '%log' => $old_log));

  node_save($node_revision);

  watchdog('content', '@type: reverted %title revision %revision.', array('@type' => $node_revision->type, '%title' => $node_revision->title, '%revision' => $node_revision->vid));
  drupal_set_message(t('@type %title has been reverted back to the revision from %revision-date.', array('@type' => node_type_get_name($node_revision), '%title' => $node_revision->title, '%revision-date' => format_date($node_revision->revision_timestamp))));
  $form_state['redirect'] = 'node/' . $node_revision->nid . '/revisions';
}

/**
 * Implements hook_admin_paths().
 *
 * Add node revision review to admin paths
 */
function os_revisions_admin_paths() {
  $paths = array(
    'node/*/revisions/*/view' => TRUE,
  );

  return $paths;
}
