<?php

function os_common_library() {
  $info = array();

  $path = drupal_get_path('os_common');
  $rest = url('api', array('alias' => true));

  $info['JSPager'] = array(
    'title' => 'JS Pager',
    'js' => array(
      $path.'/JSPager/JSPager.module.js' => array(),
      array(
        'type' => 'setting',
        'data' => array(
          'paths' => array(
            'JSPager' => $path.'/JSPager',
          )
        )
      )
    )
  );

  $info['EntityService'] = array(
    'title' => 'EntityService',
    'js' => array(
      $path.'/EntityService/EntityService.module.js' => array(),
      array(
        'type' => 'setting',
        'data' => array(
          'paths' => array(
            'api' => $rest
          )
        )
      )
    )
  );

  return $info;
}