<?php

/**
 * Implements hook_boxes_plugins.
 */
function os_migrate_demo_boxes_plugins() {
  $info = array();
  $info['os_boxes_cache_test'] = array(
    'title' => 'Just for test',
    'description' => 'Just for test',
    'tags' => array('Content'),
    'handler' => array(
      'class' => 'os_boxes_cache_test',
      'file' => 'os_boxes_cache_test.inc',
      'path' => drupal_get_path('module', 'os_migrate_demo') . '/plugins/' . '/os_boxes_cache_test',
      'parent' => 'os_boxes_default',
    ),
    'weight' => -4,
    'factory' => FALSE,
  );
  return $info;
}

/**
 * Implements hook_menu().
 */
function os_migrate_demo_menu() {

  $items = array();

  $items['os-reader/%'] = array(
    'page callback' => 'os_reader_dummy_xml',
    'access callback' => TRUE,
    'page arguments' => array(1),
  );

  $items['os-importer-demo/%'] = array(
    'page callback' => 'os_migrate_demo_import_csv',
    'access callback' => TRUE,
    'page arguments' => array(1),
  );

  return $items;
}

/**
 * Menu callback; Print a dummy xml of feeds items.
 */
function os_reader_dummy_xml($vsite_name) {
  global $base_url;
  drupal_goto($base_url . '/' . drupal_get_path('module', 'os_migrate_demo') . '/includes/' . $vsite_name . '_dummy_rss.xml');
}

/**
 * Implements hook_migrate_api().
 */
function os_migrate_demo_migrate_api() {
  $migrations = array();

  $classes = array(
    'OsMigrateAuthorsTaxonomyTerm',
    'OsMigrateBiologyTaxonomyTerm',
    'OsMigrateMathTaxonomyTerm',
    'OsMigrateScienceTaxonomyTerm',
    'OsMigratePersonalNode',
    'OsMigrateProjectNode',
    'OsMigrateBioagrphyNode',
    'OsMigratePublicationNode',
    'OsMigrateClassesNode',
    'OsMigrateClassesMaterialNode',
    'OsMigrateCurriculumVitaeNode',
    'OsMigrateNewsNode',
    'OsMigrateEventsNode',
    'OsMigrateBlogNode',
    'OsMigrateBookNode',
    'OsMigratePeopleNode',
    'OsMigrateLinkNode',
    'OsMigratePresntationsNode',
    'OsMigrateFeedsNode',
    'OsMigrateGalleryNode',
    'OsMigrateOgVocab',
    'OsMigrateUsers',
    'OsMigrateFAQNode',
    'OsMigrateSoftwareNode',
    'OsMigrateFamilyTaxonomyTerm',
    'OsMigrateDepartmentNode',
    'OsMigratePageNode',
  );

  foreach ($classes as $class_name) {
    $migrations[$class_name] = array('class_name' => $class_name);
  }

  $api = array(
    'api' => 2,
    'migrations' => $migrations,
  );
  return $api;
}
