<?php

function restful_messages_library() {
  $libs = array();

  $libs['messages'] = array(
    'title' => 'Restful Messages',
    'version' => '1.0',
    'js' => array(
      drupal_get_path('module', 'restful_messages') . '/messages.module.js' => array()
    )
  );

  return $libs;
}

function restful_messages_page_build(&$page) {
  os_common_angular_apps('Messages');
  $page['page_bottom']['messages'] = array(
    '#markup' => '<div id="messages" ng-controller="messageController">
  <div class="close-button" ng-click="close()"></div>
  <div class="error">
    <ul>
        <li ng-repeat="m in messages.errors">{{m}}</li>
    </ul>
  </div>
  <div class="status">
    <ul>
        <li ng-repeat="m in messages.status">{{m}}</li>
    </ul>
  </div>
</div>',
    '#attached' => array(
      'library' => array(
        array('restful_messages', 'messages')
      )
    )
  );
}