<?php
// $Id$

/**
 * @file
 * 
 * OS Reports module file
 */


/**
 * Implement hook_permission().
 */
function os_reports_permission() {
  return array(
    'access reports' => array(
      'title' => t('View OS Reports'),
      'description' => t('Access the OS reports.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implement hook_menu().
 */
function os_reports_menu() {
  $items = array();
  $items['admin/reports/site'] = array(
    'title' => 'Site Report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os_reports_site_form'),
    'access callback' => 'user_access',
    'access arguments' => array('access reports'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/reports/user'] = array(
    'title' => 'User Report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os_reports_user_form'),
    'access callback' => 'user_access',
    'access arguments' => array('access reports'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * OS Site report form
 */
function os_reports_site_form($form, &$form_state) {
  os_common_angular_app('ReportModule');

  $form['#attached'] = array(
    'js' => array(
      array(
        'data' => array(
          'osRestModulePath' => $GLOBALS['base_url'] . '/' . drupal_get_path('module', 'os_reports'),
          'restBasePath' => url('api'),
        ),
        'type' => 'setting',
      ),
      array (
        'data' => drupal_get_path('module', 'os_reports').'/js/ReportModule.js',
        'type' => 'file',
      ),
    ),
    'css' => array(
      drupal_get_path('module', 'os_reports') . '/os_reports.css',
      drupal_get_path('theme', 'seven') . '/style.css',
    ),
    'library' => array(
      array('os_common', 'EntityService'),
      array('os_common', 'auth'),
    )
  );

  $form['#attributes'] = array(
    'ng-controller' => 'SiteReportQuery',
    'ng-app' => 'ReportModule',
    'name' => 'queryForm',
  );
  $form['keyword_set'] = array(
    '#type' => 'fieldset',
    '#title' => 'Keyword search'
  );
  $form['keyword_set']['keyword'] = array(
    '#prefix' => '<div class="container-inline">',
    '#suffix' => '</div>',
    '#type' => 'textfield',
    '#title' => 'Keyword',
    '#attributes' => array(
      'ng-model' => 'query.keyword',
      'ng-change' => "updateParam('keyword')"
    ),
  );
  $form['keyword_set']['kfields'] = array(
    '#prefix' => '<div class="container-inline"><label for="edit-kfields">Search in fields </label>',
    '#suffix' => '</div>',
    '#type' => 'checkboxes',
  );
  $form['keyword_set']['kfields']['mail'] = array(
    '#value' => 'mail',
    '#title' => 'email',
    '#type' => 'checkbox',
    '#attributes' => array(
      'ng-model' => 'query.kfields.mail',
      'ng-click' => "updateCheckedValues('kfields', 'mail')"
    ),
  );
  $form['keyword_set']['kfields']['name'] = array(
    '#value' => 'name',
    '#title' => 'username',
    '#type' => 'checkbox',
    '#attributes' => array(
      'ng-model' => 'query.kfields.name',
      'ng-click' => "updateCheckedValues('kfields', 'name')"
    ),
  );
  $form['keyword_set']['kfields']['n.title'] = array(
    '#value' => 'n.title',
    '#title' => 'site name',
    '#type' => 'checkbox',
    '#attributes' => array(
      'ng-model' => 'query.kfields.n.title',
      'ng-click' => "updateCheckedValues('kfields', 'n.title')"
    ),
  );
   $form['lastupdate'] = array(
    '#prefix' => '<div class="container-inline">',
    '#suffix' => '</div>',
    '#type' => 'textfield',
    '#title' => 'Content last updated before',
    '#size' => 10,
    '#description' => 'format: YYYYMMDD',
    '#attributes' => array(
      'ng-model' => 'query.lastupdate',
      'ng-change' => "updateParam('lastupdate')"
    ),
  );
 $form['columns'] = array(
    '#prefix' => '<div class="container-inline"><label for="edit-columns">Optional columns </label>',
    '#suffix' => '</div>',
    '#type' => 'checkboxes',
 );
  $form['columns']['owner_email'] = array(
    '#value' => 'owner_email',
    '#title' => 'Owner email',
    '#type' => 'checkbox',
    '#attributes' => array(
      'ng-model' => 'query.columns.owner_email',
      'ng-click' => "updateCheckedValues('columns', 'owner_email')"
    ),
  );
  $form['columns']['privacy'] = array(
    '#value' => 'privacy',
    '#title' => 'Privacy level',
    '#type' => 'checkbox',
    '#attributes' => array(
      'ng-model' => 'query.columns.privacy',
      'ng-click' => "updateCheckedValues('columns', 'privacy')"
    ),
  );
  $handler = restful_get_restful_handler('report_sites');
  $form['range'] = array(
    '#value' => $handler->getRange(),
    '#type' => 'hidden',
    '#attributes' => array(
      'ng-model' => 'query.range',
      'ng-init' => "query.range = '" . $handler->getRange() . "'",
    ),
  );
  $form['buttons'] = array(
    '#prefix' => '<div class="buttons">',
    '#suffix' => '</div>',
  );
  $form['buttons']['submit'] = array(
    '#markup' => '<a class="button" ng-click="update()">Run Report</a>',
  );
  $form['buttons']['clear'] = array(
    '#markup' => '<a class="button" ng-click="reset()">Clear</a>',
  );
  $form['buttons']['download'] = array(
    '#type' => 'submit',
    '#value' => 'Download CSV of Full Report',
  );

  $buttons = '<div class="pager"><div class="container-inline"><div class="previous"><a ng-click="pager(\'previous\')">‹ previous</a></div><div class="status_count">{{ status }}</div><div class="next"><a ng-click="pager(\'next\')">next ›</a></div></div></div>';

  $form['results'] = array(
    '#markup' => $buttons . '<div class="results"><table><thead><tr><th ng-repeat="header in headers"><a ng-click="sort(this)" class="{{ header }}">{{ header | formatHeader }}</a></th></tr></thead><tbody><tr ng-repeat="row in rows" ng-class-even="\'even\'" ng-class-odd="\'odd\'"><td ng-repeat="header in headers"><span ng-bind-html="row[header] | makelink:header:row"></span></td></tr></tbody></table></div>' . $buttons,
  );

  return $form;
}

function os_reports_site_form_submit($form, &$form_state) {
  global $base_url;
  $form_state['rebuild'] = TRUE;
  
  $handler = restful_get_restful_handler('report_sites');
  $params = $form_state['input'];

  // clean up parameters before rest call
  foreach ($params as $key => $value) {
    if (!$value) {
      unset($params[$key]);
    }
    if (is_array($value)) {
      $values = array_keys($value);
      $params[$key] = $values;
    }
  }

  $params['range'] = 0;

  // make restful call to get data
  $results = $handler->post('', $params);

  if ($results) {
    $filename = str_replace("http://", "", $base_url) . "-site-report.csv";

    drupal_add_http_header("Cache-Control", "public");
    drupal_add_http_header("Content-Type", "application/octet-stream");
    drupal_add_http_header("Cache-Control", "o-store, no-cache, must-revalidate");
    drupal_add_http_header("Cache-Control", "post-check=0, pre-check=0");
    drupal_add_http_header("Content-Disposition", "attachment; filename=\"$filename\";" );
    drupal_add_http_header("Content-Transfer-Encoding", "binary");

    $headers = array_keys($results[0]);
    print ucfirst(str_replace("_", " ", implode($headers, ", "))) . "\n";
    foreach ($results as $row) {
      print implode($row, ", ") . "\n";
    }
    drupal_exit();
  }
  else {
    drupal_set_message('No results in report.', 'warning');
  }
}

/**
 * Move angular to the top of the list scripts list.
 * We need it to load before jQuery because the version in Drupal is too old.
 */
function os_reports_process_html(&$vars) {
  $search = '<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.js"></script>';
  $style = str_replace($search, '', $vars['scripts'], $count);
  if ($count) {
    $vars['scripts'] = $search . "\n" . $style;
  }
}
