<?php

/**
 * Implements hook_menu().
 */
function media_browser_menu() {
  $items['media/browser/rest'] = array(
    'title' => 'Media Browser REST',
    'page callback' => 'media_browser_media_browser',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implements hook_library().
 */
function media_browser_library() {
  $info = array();

  $bower_dir = libraries_get_path('components');

  return $info;
}

/**
 * Implements hook_library_alter().
 *
 * Replaces the old media browser code with our own
 */
function media_browser_library_alter(&$libs) {
  if (!isset($libs['media_browser'])) {
    return;
  }

  $disable = array('alias' => TRUE);
  $path = drupal_get_path('module', 'media_browser');

  include_once DRUPAL_ROOT . '/includes/file.mimetypes.inc';
  $mapping = file_mimetype_mapping();
  $types = file_type_get_enabled_types();
  $map = array();
  foreach ($types as $t => $info) {
    $map[$t] = _os_files_extensions_from_type($t);
  }

  $libs['media_browser']['js'] += array(
    $path . '/misc/MediaBrowserFilters.js' => array(),
    $path . '/misc/MediaBrowserModule.js' => array(),
    array(
      'data' => array(
        'paths' => array(
          'moduleRoot' => url(drupal_get_path('module', 'media_browser'), $disable),
        ),
        'version' => array(
          'mediaBrowser' => '0.9'
        ),
        'extensionMap' => $map,
        'maximumFileSize' => ini_get('upload_max_filesize'),
        'maximumFileSizeRaw' => parse_size(ini_get('upload_max_filesize')),
      ),
      'type' => 'setting',
    )
  );

  $libs['media_browser']['dependencies'] = array_merge($libs['media_browser']['dependencies'], array(
    array('os_common', 'JSPager'),
    array('os_common', 'EntityService'),
    array('os_common', 'FileEditor'),
    array('os_common', 'ng-file-upload'),
    array('os_common', 'auth'),
    array('os_common', 'angular-modal-service')
  ));

  $libs['media_browser']['css'] = array(
    $path.'/misc/media_browser.mediaBrowser.css',
  );

  // We don't need any of this stuff anymore  or even this library. Can't delete
  // it though.
//  $libs['media_browser_page']['js'] = array();
//  $libs['media_browser_page']['css'] = array();
//  $libs['media_browser_page']['dependencies'] = array();
}

/**
 * Implements hook_element_info_alter().
 */
function media_browser_element_info_alter(&$elements) {
  $elements['media']['#process'][] = 'media_browser_element_process';
}

/**
 * Implements hook_field_widget_form_alter().
 */
function media_browser_field_widget_media_generic_form_alter(&$elements, &$forms_state, $context) {
  if ($size = $elements['#media_options']['global']['max_filesize']) {
    $elements['#media_options']['global']['max_filesize_raw'] = parse_size($size);
  }
  else {
    $size = ini_get('upload_max_filesize');
    $elements['#media_options']['global']['max_filesize'] = $size;
    $elements['#media_options']['global']['max_filesize_raw'] = parse_size($size);
  }
  //$elements['#process'][] = 'media_browser_element_process';
}

/**
 * Replaces the original media element's launcher buttons with our directive
 */
function media_browser_element_process($elem, $form_state, $form) {
  return $elem;

  $elem['preview']['#prefix'] = '<div class="preview" mb-open-modal>';

  $elem['select']['#attributes']['mb-open-modal'] = '';
  $elem['select']['#attributes']['class']
    = array_diff($elem['select']['#attributes']['class'], array(
    'launcher'
  ));

  return $elem;
}

/**
 * Implements hook_wysiwyg_include_directory().
 */
function media_browser_wysiwyg_include_directory($type) {
  switch ($type) {
    case 'plugins':
      return 'wysiwyg_plugins';
  }
}

/**
 * Deprecated
 */
function media_browser_restws_response_alter(&$response, $function) {
  switch ($function ) {
    case 'queryResource':
      foreach ($response['list'] as $k => $f) {
        $response['list'][$k] = _media_browser_modify_response_row($f);
      }
      break;
    case 'viewResource':
        $response = _media_browser_modify_response_row($response);
      break;
  }
}

/**
 * Deprecated
 */
function _media_browser_modify_response_row($file) {
  $blacklist = array(
    'og_group_ref' => TRUE,
    'og_membership' => TRUE,
    'og_membership__1' => TRUE,
    'og_membership__2' => TRUE,
    'og_membership__3' => TRUE,
    'og_group_ref__og_membership' => TRUE,
    'og_group_ref__og_membership__1' => TRUE,
    'og_group_ref__og_membership__2' => TRUE,
    'og_group_ref__og_membership__3' => TRUE,
  );

  $filtered = array_diff_key($file, $blacklist);

  $f = file_load($file['fid']);
  $filtered['orig'] = $f->origname;
  $filtered['preview'] = drupal_render(file_view_file($f, 'preview'));
  switch ($filtered['type']) {
    case 'image':
      $filtered['form'] = 'file_edit_image';
      break;
    default:
      $filtered['form'] = 'file_edit_default';
  }
  entity_get_controller('file')->resetCache();

  return $filtered;
}

/**
 * Media Browser callback
 */
function media_browser_media_browser() {
  $root = $GLOBALS['base_url'] . '/' . drupal_get_path('module', 'media_browser') . '/templates/';
  $misc_patch =  drupal_get_path('module', 'media_browser') . '/misc/';

  $browser = array(
    '#prefix' => '<div ng-app="mediaBrowser"><div ng-include="\'' . $root . 'browser.html'.'\'" ng-controller="BrowserCtrl">',
    '#suffix' => '</div></div>',
    '#attached' => array(
      'js' => array(
        array(
          'data' => array(
            'osRestModulePath' => $GLOBALS['base_url'] . '/' . drupal_get_path('module', 'media_browser'),
            'restBasePath' => url('api'),
          ),
          'type' => 'setting',
        ),
        array (
          'data' => $misc_patch . 'MediaBrowserFilters.js',
          'type' => 'file',
          'scope' => 'footer',
        ),
        array (
          'data' => $misc_patch . 'MediaBrowserDirectives.js',
          'type' => 'file',
          'scope' => 'footer',
        ),
        array (
          'data' => $misc_patch . 'MediaBrowserServices.js',
          'type' => 'file',
          'scope' => 'footer',
        ),
        array (
          'data' => $misc_patch . 'MediaBrowserModule.js',
          'type' => 'file',
          'scope' => 'footer',
        )
      ),
      'css' => array(
        $misc_patch . 'media_browser.mediaBrowser.css',
      ),
      'library' => array(
        array('os_common', 'JSPager'),
        array('os_common', 'EntityService'),
        array('media_browser', 'ng-file-upload'),
        array('os_common', 'auth'),
        array('os_common', 'angular-modal-service')
      )
    )
  );

  return $browser;
}

/**
 * Move angular to the top of the list scripts list.
 * We need it to load before jQuery because the version in Drupal is too old.
 */
function media_browser_process_html(&$vars) {
  $search = '<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.js"></script>';
  $style = str_replace($search, '', $vars['scripts'], $count);
  if ($count) {
    $vars['scripts'] = $search . "\n" . $style;
  }
}
