<?php

use Guzzle\Http\Message;
function admin_panel_preprocess_page(&$vars) {
	if (user_is_logged_in()) {
    drupal_add_library('admin_panel','admin_panel');
    os_common_angular_app('AdminPanel');
	}
}

function admin_panel_page_build(&$vars) {
  $am = <<<AM

<!-- new admin_panel -->
<div class="morph-button morph-button-sidebar morph-button-fixed" ng-controller="MenuCtrl">
      <button type="button"></button>
      <div class="morph-content">
        <div>
          <div class="content-style-sidebar">
            <a href="/path/to/vsite-homepage" class="admin-menu-homeicon"></a>
            <div class="close_panel">
              <span style="color:#a39d9d;">O</span><span style="color:#df1f26;">S</span>
            </div><span class="icon icon-close">&#171; Close</span>
            <div id='cssmenu'>
              <ul>
                <li>&nbsp;</li>
                <li ng-repeat="(key, parent) in admin_panel" ng-class="{'has-sub': parent.children}">
                  <a ng-attr-href="{{parent.href || '#'}}" toggle-open ng-class="{'toggleable': parent.children}">{{ parent.label }}</a>
                  <ul class='sub-menu' ng-if="parent.children" ng-repeat="(key, child) in parent.children">
                    <li class='submenu' ng-class="{'has-sub': child.children, 'heading': child.type == 'heading'}">
                      <a href="{{child.href || '#'}}" toggle-open ng-class="{'toggleable': child.children, 'submenu_heading': child.children}">{{ child.label }}</a>
                      <ul ng-if="child.children">
                        <li ng-repeat="(key, grandchild) in child.children">
                          <a ng-attr-href="{{ grandchild.href || '#' }}">{{ grandchild.label }}</a>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </li>
                <!--REMOVE THIS LI WHEN BETA TESTING IS COMPLETE-->
                <li style="margin-top:70px;">
                  <a href='https://harvard.az1.qualtrics.com/SE/?SID=SV_5pErjqW6E44JV0p' target="_blank" style="background: #222;">Feedback Form</a>
                  </li>

              </ul>

            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- new admin_panel -->
AM;

  $vars['page_bottom']['admin_menu'] = array(
    '#weight' => 25,
    '#markup' => $am,
  );
}

/**
 * Implements hook_library_alter().
 *
 * Adds code for the admin panel
 */
function admin_panel_library() {

  $disable = array('alias' => TRUE);
  $path = drupal_get_path('module', 'admin_panel');

  // Includes resources needed to create the admin panel.
  $libs['admin_panel'] = array(
    'title' => 'Admin Panel libraries',
  );

  $libs['admin_panel']['js'] = array(
    $path . '/misc/AdminPanelModule.js' => array(),
    $path . '/misc/classie.js' => array(),
    $path . '/misc/modernizr.custom.js' => array(),
    $path . '/misc/uiMorphingButton_fixed.js' => array(),
    $path . '/misc/admin_panel.js' => array(),
    array(
      'data' => array(
        'paths' => array(
          'moduleRoot' => url($path, $disable),
        ),
        'version' => array(
          'adminPanel' => '0.0.1'
        ),
      ),
      'type' => 'setting',
    )
  );

  $libs['admin_panel']['dependencies'] = array(
    array('os_common', 'auth'),
    array('os_common', 'helpers'),
  );

  $libs['admin_panel']['css'] = array(
    $path.'/misc/component.css',
    $path.'/misc/content.css',
    $path.'/misc/admin_panel-menu.css',
  );

  return $libs;
}