<?php

/**
 * Implements hook_preprocess_page().
 *
 * Adds the user_panel angular library.
 */
function admin_panel_preprocess_page(&$vars) {
	if (user_is_logged_in() && variable_get('admin_panel_enabled', FALSE)) {
    drupal_add_library('admin_panel','user_panel');
    os_common_angular_apps('UserPanel');
	}
}

/**
 * Implements hook_page_build().
 *
 * Adds the admin_panel angular markup and wrapper.
 */
function admin_panel_page_build(&$vars) {

  // No need for admin-panel markup
  if (!user_is_logged_in() || !variable_get('admin_panel_enabled', FALSE)) {
    return;
  }

  $vars['page_bottom']['admin_menu'] = array(
    '#weight' => 25,
    '#markup' => '<div class="morph-button no-transition morph-button-sidebar morph-button-fixed" left-menu></div>',
  );

  $vars['page_bottom']['user_menu'] = array(
    '#weight' => 25,
    '#markup' => '<div right-menu></div>',
  );
}

/**
 * Implements hook_library_alter().
 *
 * Adds code for the admin panel
 */
function admin_panel_library() {

  global $user;
  $disable = array('alias' => TRUE);
  $path = drupal_get_path('module', 'admin_panel');
  $perm = drupal_static('user_access');
  $spaces_features = variable_get('spaces_features', array());
  $vsite = vsite_get_vsite();

  // Includes resources needed to create the admin panel.
  $libs['admin_panel'] = array(
    'title' => 'Admin Panel libraries',
    'version' => '0.0.1',
  );

  $perms = isset($perm[$user->uid]) ? $perm[$user->uid] : array();
  // Create a unique cid based on user permissions and enabled features.
  $cid = drupal_hash_base64(implode("",array_merge(array_filter($spaces_features),$perms)));

  $libs['admin_panel']['js'] = array(
    $path . '/misc/AdminPanelModule.js' => array(),
    $path . '/misc/modernizr.custom.js' => array(),
    $path . '/misc/uiMorphingButton_fixed.js' => array(),
    array(
      'data' => array(
        'paths' => array(
          'adminPanelModuleRoot' => url($path, $disable),
        ),
        'admin_panel' => array(
          'user' => $user->uid,
          'cid' => $cid,
          //The menu should stay open if we are in an administrative area.
          'keep_open' => !context_isset('context', 'os_public'),
        ),
        'version' => array(
          'adminPanel' => '0.0.2'
        ),
      ),
      'type' => 'setting',
    )
  );

  $libs['admin_panel']['dependencies'] = array(
    array('os_common', 'auth'),
    array('os_common', 'helpers'),
  );

  $libs['admin_panel']['css'] = array(
    $path.'/misc/component.css',
    $path.'/misc/content.css',
    $path.'/misc/admin_panel-menu.css',
  );

  $libs['user_panel']['version'] = '0.0.2';
  $libs['user_panel']['js'] = array(
    $path . '/misc/UserPanelModule.js' => array(),
    array(
      'data' => array(
        'user_panel' => array(
          'user' => array(
            'uid' => $user->uid,
            'name' => format_username($user),
            'support_user' => user_access('subscribe as support team'),
            'is_member' => ($vsite) ? og_is_member('node', $vsite->id) : false,
          ),
        ),
        'version' => array(
          'userPanel' => '0.0.1'
        ),
        'paths' => array(
          'support_subscribe' => ($vsite) ? $vsite->get_absolute_url('group/node/' . $vsite->id . '/subscribe/vsite_support_expire') : '',
          'support_unsubscribe' => ($vsite) ? $vsite->get_absolute_url('group/node/' . $vsite->id . '/unsubscribe') : '',
        ),
      ),
      'type' => 'setting',
    )
  );
  $libs['user_panel']['dependencies'] = array(
    array('admin_panel', 'admin_panel'),
    array('google_feedapi', 'google_jsapi_feeds'),
    array('os_tour', 'hopscotch'),
    array('os_tour', 'os_tour'),
  );

  return $libs;
}

/**
 * Implements hook_admin_paths().
 */
function admin_panel_admin_paths() {
  $items = array(
    'group/node/*/subscribe/vsite_support_expire' => TRUE,
    'group/node/*/unsubscribe' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_cp_settings().
 *
 * Temp allow admin panel to be enbabled conditionally
 */
function admin_panel_cp_settings() {
  $setting = array();
  $setting['admin_panel_enabled'] = array(
    'group' => array(
      '#title' => t('UX/UI Beta Options'),
      '#id' => 'ux-ui',
    ),
    'form' => array(
      '#type' => 'checkbox',
      '#default_value' => variable_get('admin_panel_enabled', FALSE),
      '#title' => t('Enable the Admin Panel Beta'),
      '#description' => t('Checking this will switch this site to use the new beta admin panel.  This will impact all users of this site.  Deselecting will revert to the old menu.'),
      // Use existing access permission since this is just temporary.
      '#access' => user_access('change vsite domain'),
    ),
  );

  return $setting;
}