<?php
/**
 * os_settings.module
 */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 */
function os_settings_form_system_site_information_settings_alter(&$form, &$form_state, $form_id){
  
  //Configurable default physical address to be displayed in email footer
  $form['site_information']['site_physical_address'] = array(
    '#type' => 'textfield',
    '#title' => t("Physical Address"),
    '#default_value' => variable_get('defaultEmailFooter',"Massachusetts Hall, Cambridge, MA 02138"),
    '#description' => t("The physical address to be displayed in the footer of all emails triggered from this site."),
    '#required' => TRUE,
  );
  
  //Configurable default from email address to be displayed in 'from' for all emails
  $form['site_information']['site_from_email'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get('defaultFromAddress',"hwp@harvard.edu"),
    '#title' => t("Sender email address"),
    '#description' => t("The email address to be displayed in the 'from' field of all emails triggered from this site."),
    '#required' => TRUE,
  );
  
  //Custom submit handler to save the values in variables table
  $form['#submit'][] = '_save_site_information_values';
}

//Submit function to save the values
function _save_site_information_values(&$form, &$form_state){
  
  //Save the default physical address
  $site_physical_address = $form_state['values']['site_physical_address'];
  variable_set('defaultEmailFooter',$site_physical_address);
  
  //Save the default from email address
  $site_from_email = $form_state['values']['site_from_email'];
  variable_set('defaultFromAddress',$site_from_email);
}

/**
 * Implements hook_mail_alter().
 */
function os_settings_mail_alter(&$message) {
  
  //An array containing all the events related emails keys.
  $eventEmailArr = array("broadcast","registration_confirmation","event_cancel_notification","event_time_updated_notification");
  
  //Update the from email address for all emails except events related emails.
  if(!in_array($message['key'],$eventEmailArr)) {
    
    // Set default value of the "From" field.
    $message['headers']['From'] = $message['from'] = variable_get('defaultFromAddress',"hwp@harvard.edu");

    //Set the sender and return-path headers.
    $message['headers']['Sender'] = $message['headers']['Return-Path'] = $message['headers']['From'];
  }
  
  //Adding the footer physical address for all emails
  $message['body'][] = '';
  $message['body'][] = variable_get('defaultEmailFooter',"Massachusetts Hall, Cambridge, MA 02138");
}