<?php

define('OS_SITE_CREATION_FORM', '1.0.0');

function os_site_creation_library() {
  $libs = array();
  $self = drupal_get_path('module', 'os_site_creation');
  $disable = array('alias' => TRUE);
  $libs['module'] = array(
    'title' => 'Site Creation Form',
    'version' => OS_SITE_CREATION_FORM,
    'js' => array(
      $self.'/osSiteCreation.module.js' => array(),
      array(
        'data' => array(
          'paths' => array(
            'siteCreationForm' => url($self.'/templates', $disable),
          ),
          'version' => array(
            'siteCreationForm' => OS_SITE_CREATION_FORM,
          )
        ),
        'type' => 'setting',
      )
    ),
    'css' => array(
      drupal_get_path('theme', 'cp_theme') . '/css/cp_theme.css' => array(
        'group' => CSS_THEME,
        'every_page' => TRUE,
        'media' => 'screen'),
    ),
    'dependencies' => array(
      array('os_common', 'angular-modal-service'),
      array('os_common', 'formElement'),
      array('os_common', 'buttonSpinner'),
      array('ap_settings_form', 'redirect')
    )
  );
/*
  $libs['redirect'] = array(
    'title' => 'Redirect Form',
    'version' => '0.1',
    'js' => array(
      $self.'/redirects.module.js' => array()
    )
  );
*/
  return $libs;
}

function os_site_creation_library_alter(&$libs) {
  if (isset($libs['admin_panel'])) {
    $libs['admin_panel']['dependencies'][] = array('os_site_creation', 'module');
  }
}