<?php

define('OS_SITE_CREATION_FORM', '1.0.0');

/**
 * Implements hook_menu().
 */
function os_site_creation_menu() {
  $items['sitecreation/validate/%'] = array(
    'page callback' => '_os_site_creation_get_exiting_sites',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  $items['sitecreation/savedata'] = array(
    'page callback' => '_os_site_save_data',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Callback save site creation data.
 */
function _os_site_save_data() {
  $postData = json_decode($_POST['formdata']);

  if($postData->individualScholar != "") {
    $formData['bundle'] = 'personal';
    $formData['domain'] = $postData->individualScholar;
  } else if($postData['projectLabSmallGroup'] != "") {
    $formData['bundle'] = 'project';
    $formData['domain'] = $postData->projectLabSmallGroup;
  } else {
    $formData['bundle'] = 'department';
    $formData['domain'] = $postData->departmentSchool;
  }
  $formData['preset'] = $postData->contentOption;
  $formData['vsite_private'] = $postData->vsite;

  print_r($formData);
  die();
}

/**
 * Callback to return JSON encoded output.
 */
function _os_site_creation_get_exiting_sites($siteValue) {
  //Validate new vsite URL
  if (strlen($siteValue) < 3 || !valid_url($siteValue)) {
    drupal_json_output("Invalid");
  }
  else if (($purl = purl_load(array('value' => $siteValue, 'provider' => 'spaces_og'), TRUE)) || menu_get_item($siteValue)) {
    drupal_json_output("Not-Available");
  }
  else {
    drupal_json_output("Available");
  }
}


/**
 * Implements hook_library().
 */
function os_site_creation_library() {
  $libs = array();
  $self = drupal_get_path('module', 'os_site_creation');
  $disable = array('alias' => TRUE);
  $libs['site_creation'] = array(
    'title' => 'Site Creation Form',
    'version' => OS_SITE_CREATION_FORM,
    'js' => array(
      $self.'/osSiteCreation.module.js' => array(),
      $self.'/misc/js/os_site_creation.js' => array(),
      $self.'/misc/js/messages.min.js' => array(),
      array(
        'data' => array(
          'paths' => array(
            'siteCreationForm' => url($self.'/templates', $disable),
            'siteCreationModuleRoot' => url(drupal_get_path('module', 'os_site_creation'), $disable),
          ),
          'version' => array(
            'siteCreationForm' => OS_SITE_CREATION_FORM,
          )
        ),
        'type' => 'setting',
      )
    ),
    'css' => array(
      drupal_get_path('module', 'os_site_creation') . '/misc/css/os_site_creation.css' => array(
      'group' => CSS_THEME,
      'every_page' => TRUE,
      'media' => 'screen'),
    ),
    'dependencies' => array(
      array('os_common', 'angular-modal-service'),
      array('os_common', 'formElement'),
      array('os_common', 'buttonSpinner'),
      array('ap_settings_form', 'redirect')
    )
  );
  return $libs;
}

/**
 * Implements hook_library_alter().
 *
 */
function os_site_creation_library_alter(&$libs) {
  if (isset($libs['admin_panel'])) {
    $libs['admin_panel']['dependencies'][] = array('os_site_creation', 'site_creation');
  }
}
