<?php 

/**
 * Blog revert - blog uses infinite scroll.
 */
function os_blog_update_7001() {
  features_revert(array('os_blog' => 'view'));
}

/**
 * Delete the bookmark flag from blogs.
 */
function os_blog_update_7002() {
  module_load_include('module', 'flag');
  try {
    if ($flag = flag_get_flag('bookmarks')) {
      $flag->delete();
    }
  }
  catch (Exception $e) {
    // something went wrong. We don't really care what. Log it anyway.
    watchdog("error", $e->getMessage());
  }
}
